### ISSUE TITLE
Absence de fond de carte, erreur GET france-vector.json

### ISSUE THREAD

**Issue by StephaneColson** [benoitdemaegdt/voieslyonnaises#212]
Visiblement le fond de carte (osm) n'est plus chargé sur la carte interactive ni sur les carte des lignes.

Un problème avec france-vector qui n'est pas complétement téléchargé (98,24 ko sur 378, 41 ko) !?

![CleanShot 2023-11-26 at 13 17 30@2x](https://github.com/benoitdemaegdt/voieslyonnaises/assets/1481595/474bad2e-56ea-43c8-8b05-6fb4aa7eafb7)

![CleanShot 2023-11-26 at 13 19 22@2x](https://github.com/benoitdemaegdt/voieslyonnaises/assets/1481595/f5f243dd-dfef-4070-8704-0d1443373011)

![CleanShot 2023-11-26 at 13 21 55@2x](https://github.com/benoitdemaegdt/voieslyonnaises/assets/1481595/1c59904f-c027-4178-869a-b2128cca86fb)

![CleanShot 2023-11-26 at 13 24 02@2x](https://github.com/benoitdemaegdt/voieslyonnaises/assets/1481595/0694ae9c-fd98-48d2-b271-a0e8c34a28c0)

**Comment by benoitdemaegdt** [comment]
Aïe aïe aïe, merci pour l'info ...
Pas sur que je puisse y faire grand chose. Je vois avec data gouv si ils ont un problème avec leur serveur de tuiles

**Comment by benoitdemaegdt** [comment]
Ticket support créé à l'instant.
Dans le meilleur des cas, on peut s'attendre à un retour demain 🙏

**Comment by benoitdemaegdt** [comment]
En attendant, j'ai remplacé par un autre fond de carte (mais payant à partir d'un certain usage, donc ce serait cool que l'ancien refonctionne :) )
