### ISSUE TITLE
[Design] Refonte page des compteurs

### ISSUE THREAD

**Issue by benoitdemaegdt** [benoitdemaegdt/voieslyonnaises#222]
En haut de la page individuelle des compteurs, il y a aujourd'hui une photo qui présente peu d'intérêt.

On propose de remplacer par une carte interactive, qui montre la position du compteur.

<img width="1048" alt="image" src="https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/7902b18a-af06-4c60-bfde-79f4211f488c">

**Comment by benoitdemaegdt** [comment]
fait ici https://github.com/benoitdemaegdt/voieslyonnaises/commit/308474f88eae220e68a10550828e39e7cce0e420

**Comment by benoitdemaegdt** [comment]
L'idée serait maintenant d'améliorer le tooltip, un peu triste pour le moment.

![Capture d’écran 2023-12-06 à 23 09 06](https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/1d0c0bf1-0a2e-4fc6-ae98-a7993d9a6ad9)

**Comment by Delapouite** [comment]
Le site eco-counter.com d'où proviennent les données propose aussi une galerie photo pour certains compteurs.

![image](https://github.com/benoitdemaegdt/voieslyonnaises/assets/39315/253ff7e9-9654-4fab-89e7-8a066ca637d1)

Sait-on si ces photos sont publiées sous license permissive ? Est-ce que ça serait pertinent de la rapatrier afin de les inclure sur les pages des compteurs ?

**Comment by benoitdemaegdt** [comment]
Non aucune idée, je vais essayer de leur demander.
Mais je n'ai plus trop de réponse de leur part en ce moment ^^

Autre idée : simplement afficher le dernier record mensuel absolu en dessous (fond blanc, texte noir).
