### ISSUE TITLE
[Data] Typologie des aménagements

### ISSUE THREAD

**Issue by benoitdemaegdt** [benoitdemaegdt/voieslyonnaises#224]
Les `properties` des tronçons terminés ressemblent aujourd'hui à ça : 

```
"properties": {
  "id": "GdeBretagne-commun",
   "line": 1,
   "name": "Avenue de Grande-Bretagne",
    "status": "done",
    "doneAt": "28/03/2023"
},
```

Il manque une donnée intéressante pour bien analyser la qualité des aménagements livrés : le type de tronçon.

Exemple : "bidirectionnelle", "bande-cyclable", "voie-bus" etc ...

Avec ces données, on pourrait vraiment suivre de près la promesse de qualité des voies lyonnaises.

**Comment by benoitdemaegdt** [comment]
j'ai ouvert une début de PR ici, à voir si ça vaut le coup d'être repris ou pas
https://github.com/benoitdemaegdt/voieslyonnaises/pull/203

**Comment by benoitdemaegdt** [comment]
Dans un 1er temps, il faudrait déjà déterminer la liste des aménagements possibles : 
- "bidirectionnelle"
- "voie-bus"
- "velorue"
- "voie-verte"
- ... ?

Des idées pour compléter la liste @ThibautChd  ?

**Comment by ThibautChd** [comment]
A ajouter :
> Piste bilatérale
> Voie bus élargie
> Bandes cyclables
> Zone de rencontre
> Inconnu (qd on a aucune info sur le projet attendu sur ce tronçon)

**Comment by benoitdemaegdt** [comment]
ok, je viens de rajouter les types dans un check github qui s'appliquera pour le moment uniquement sur les tronçons en "done".
la liste des type qu'on peut utiliser : 
```
                    'bidirectionnelle',
                    'bilaterale',
                    'voie-bus',
                    'voie-bus-elargie',
                    'velorue',
                    'voie-verte',
                    'bandes-cyclables',
                    'zone-de-rencontre',
                    'inconnu'
```

**Comment by ThibautChd** [comment]
Ok parfait, je vais regarder pour commencer à enrichir nos tronçons avec ce statut.
Pourrais tu me donner un exemple concret de code pour en rajouter un dans nos json ? Merci :)

**Comment by benoitdemaegdt** [comment]
oui, j'ai déjà commencé dans cette PR, il faudrait idéalement ajouter les commits direct dessus.
👉  https://github.com/benoitdemaegdt/voieslyonnaises/pull/203

**Comment by benoitdemaegdt** [comment]
Pour changer de branche sur github codespace, ça se passe comme ça.
Ensuite des commits iront sur la bonne branche :) 
<img width="672" alt="image" src="https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/e6f69807-70f3-4a24-b73a-2a65a3ae930f">

**Comment by benoitdemaegdt** [comment]
terminé. Well done @ThibautChd  🙌 
https://github.com/benoitdemaegdt/voieslyonnaises/pull/203
