### ISSUE TITLE
[Dev] Créer une page tableau de bord

### ISSUE THREAD

**Issue by benoitdemaegdt** [benoitdemaegdt/voieslyonnaises#225]
On voudrait avoir un tableau de bord général, qui permette d'avoir une vision détaillée de chaque voie lyonnaise.

Voici quelques maquettes de @ThibautChd 

![Image](https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/f35e0a47-8631-45b5-bc09-b50832f0ef2a)
![Image](https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/e63720c7-4fee-4a58-bfed-2764eab8229e)

**Comment by Delapouite** [comment]
Première ébauche par page de Voie Lyonnaise dispo ici: https://github.com/benoitdemaegdt/voieslyonnaises/pull/319

![image](https://github.com/benoitdemaegdt/voieslyonnaises/assets/39315/e3c41927-2c1f-4215-b1db-74132f541fd9)

**Comment by benoitdemaegdt** [comment]
je clôture cette issue.
le tableau de bord a été ajouté ici :) 

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/c32732ac-876b-4499-986c-1563f50fcda7">
