### ISSUE TITLE
Ajout de anchor-links pour les tronçons

### ISSUE THREAD

**Issue by Delapouite** [benoitdemaegdt/voieslyonnaises#236]
Bonjour.

En essayant de faire un hyperlien depuis une source extérieure pointant vers la description d'un tronçon précis sur la page d'une voie lyonnaise je me suis rendu compte que la tache n'était pas facilitée.

J'ai tenté de faire la modif, mais Nuxt n'a pas été mon grand copain. Ce que j'avais en tete, est qu'au survol sur les `h2`, `h3`, un petit icone discret d'ancre apparait en début de la ligne.

Manifestement, c'était possible de le faire assez nativement en des temps préhistoriques (2021), mais pour des raisons obscures de framework instable, la recette ne marche plus telle-quelle. https://dev.to/armiedema/add-clickable-anchor-links-to-headers-in-nuxt-content-342d 

Mes essais:

```js
 tags: { h1: 'h1', h2: 'h2', h3: 'h3', h4: 'h4', h5: 'h5', h6: 'h6' }
```
En enlevant cette section dans `nuxt.config.ts`, des liens automatiques sont bien créés pour chaque header. Mais tout le header est wrappé. Coté `rehype`, je vois que le plugin de jadis était capable de faire un `prepend` par defaut, mais impossible de s'en sortir avec la nouvelle option `autoLinks` de Nuxt. https://github.com/rehypejs/rehype-autolink-headings

Aussi il faut penser à changer le `router.options.ts`, pour avoir une comportement lègèrement différent d'auto-scroll pour les liens avec ancre pour tenir compte du fixed header.

Si qqn a la sauce magique pour le faire sans gros bouleversement, ça serait super. Merci.

**Comment by benoitdemaegdt** [comment]
Hello 👋 

je commence à m'intéresser à ce point, par j'aimerais bien avoir ce comportement pour rediriger vers la description d'un tronçon spécifique depuis un click sur un tronçon de la carte.

Merci pour les détails dans cette issue, ça va aider :) 

<img width="426" alt="image" src="https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/c1bfddea-f44c-476b-9da1-ba16541abe88">

**Comment by benoitdemaegdt** [comment]
ça fonctionne désormais. Je ferme cette issue.
Merci 🙏
