### ISSUE TITLE
Les voies du seigneur sont impénétrables

### ISSUE THREAD

**Issue by LaSylv** [benoitdemaegdt/voieslyonnaises#31]
Super projet !

Par contre 404 quand on clique sur une voie via la.page d'acceuil :/

**Comment by benoitdemaegdt** [comment]
> Les voies du seigneur sont impénétrables

Seigneur, donne nous notre commit de ce jour 🙏 
Et voilà qui est corrigé, une sombre erreur de redirection lors d'une réorganisation du site.
Merci, chevalier blanc pour votre vigilance !
