### ISSUE TITLE
compteur vs counter

### ISSUE THREAD

**Issue by Delapouite** [benoitdemaegdt/voieslyonnaises#358]
Salut Benoit.

Au sein de la code-base nous sommes atteints d'une petit forme de franglish avec tantôt des noms de variables du style "compteur" et tantôt "counter". :)

Dans quel sens vois-tu tendre l'homogénéisation de ce nommage ?

**Comment by benoitdemaegdt** [comment]
tout le monde est d'accord, je ferme cette issue =)
