### ISSUE TITLE
Représentation des compteurs sur la carte

### ISSUE THREAD

**Issue by benoitdemaegdt** [benoitdemaegdt/voieslyonnaises#365]
### Description
Actuellement, on représente les compteurs sur la carte avec des pastilles bleues.
Il y a une autre règle : si le compteur est dans le top 10 en terme de volume de cyclistes, il est plus gros.

ça ressemble donc à ça : 
<img width="1172" alt="image" src="https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/ca643347-1baa-4434-a79c-732260078ea2">

Mais cette règle du top 10 est trop implicite. ça me semble très peu probable qu'un visiteur de la plateforme comprenne cette règle.

Si on regarde du côté de Airbnb, il ajoute de l'info directement dans la pastille.
En l'occurence le prix de la location pour la date sélectionnée.

<img width="543" alt="image" src="https://github.com/benoitdemaegdt/voieslyonnaises/assets/25749578/2a996e10-f4e7-4aec-8932-a49450f56457">

Je trouve ça assez inspirant, on pourrait mettre : 
- soit le volume du mois passé
- soit la différence (en %) vs 12 mois dans le passé, en rouge ou en vert en fonction de l'évolution.

**Comment by ThibautChd** [comment]
Personnellement pas emballé par cette proposition.
Le système d'Airbnb mis en exemple a plusieurs inconvénient pour notre cas d'usage à nous : il masque la plupart des "compteurs" pour n'afficher qu'une sélection de ceux-ci.
En outre, afficher un trafic mensuel prend bien plus de place qu'un prix en €, car on aura 4 ou 5 chiffres à faire rentrer et ça va vite surcharger la carte de chiffres.
Enfin, afficher la différence en % dans ces pastilles ne me semble pas approprié car cette fluctuation d'une année à l'autre n'est pas stable et apporte une information fortement tronquée. Il faudrait afficher une tendance linéaire sur 5ans pour avoir quelque chose qui a du sens dans ce type d'affichage?

Perso le top 10 avec des points plus gros que les autres m'allait bien. Pour rendre le truc plus clair, je partirais plutôt sur l'ajout d'un commentaire explicite à côté de la carte : "les 10 compteurs avec le trafic du dernier mois le plus important apparaissent plus grands".
