### ISSUE TITLE
Bug: liens cassés

### ISSUE THREAD

**Issue by XioNoX** [benoitdemaegdt/voieslyonnaises#405]
C'est mineur :)

1. aller sur https://cyclopolis.fr/compteurs/velo
2. aller dans le menu lignes et cliquer sur une au hasard
3. Par example https://cyclopolis.fr/compteurs/voie-lyonnaise-2
4. Erreur 404

**Comment by benoitdemaegdt** [comment]
Aïe, c'est pas terrible ça :( 

Merci pour le retour, je regarde dès que j'ai un moment 👀

**Comment by benoitdemaegdt** [comment]
Hello @XioNoX 👋 

C'est corrigé. Merci pour la remontée de bug 🙌
