### ISSUE TITLE
Sens du type d'amenagement "aucun"

### ISSUE THREAD

**Issue by TFCx** [benoitdemaegdt/voieslyonnaises#407]
Il y a actuellement des aménagements avec le `type` `aucun` : ça me paraitrait + logique de basculer ça vers un `status` `abandonné` quitte à ce que la visualisation marque "reporté".
Après ces aménagements pourraient toujours avoir un type connu ou inconnu.

Actuellement, le fait qu'une section n'a "aucun aménagement" semble plutôt indiquer qu'il n'y a aucun aménagement prévu (= mixité avec les motorisées) ? Qqn a Mplt pensait que ça signifiait qu'il n'y avait aucun aménagement aujourd'hui et qu'on ne savait pas vers quoi ils voulaient réaménager... mais ça semble logique que ce cas soit traité par inconnu`.

**Comment by ThibautChd** [comment]
Salut Jean-David,

Tu mets le doigts sur une question de méthodologie sur laquelle on s'est arraché les cheveux avec Benoit.

Finalement, on a décidé de traiter la problématique de deux manières : le statut d'avancement et le type d'aménagement, sachant que ce dernier est systématiquement projeté à la fin du mandat, horizon 2026. Autrement dit, si un tronçon est prévu ou en travaux, c'est le type attendu en 2026 qui est indiqué. S'il est inconnu, le type est mécaniquement inconnu aussi. S'il est reporté, cela signifie qu'il n'y aura aucun nouvel aménagement en fin de mandat, donc le type bascule sur l'aménagement actuel. S'il n'y a pas d'aménagement aujourd'hui (mixité totale avec motorisés sans restriction du flux de circulation), il apparait donc en "aucun".

J'espère avoir été complet et clair. N'hésite pas à revenir vers moi si besoin ;-)

**Comment by TFCx** [comment]
Ok, du coup ça me parait tout à fait logique de le garder (et peut être de le renommer à l'affiche en "aucun aménagement" voir en "mixité avec motorisés"). Le `type` indiquera donc bien l'aménagement _à terme_ (sachant qu'il peut être `inconnu`). Mais dans le cas où un segment est abandonné, son type "à terme" correspond au type actuel (qui peut du coup être `mixité avec motorisés`).

Je ferme le ticket.
