### ISSUE TITLE
Harmoniser "status": "unknown", et "type": "inconnu",

### ISSUE THREAD

**Issue by XioNoX** [benoitdemaegdt/voieslyonnaises#414]
Avoir une valeur en français et une autre en anglais porte à confusion. Serait-ce possible d'en utiliser une ou l'autre pour les 2 variables ?

**Comment by benoitdemaegdt** [comment]
Hello @XioNoX  👋 

Il y a en effet pas mal de franglais dans le code cyclopolis, ce qui peut porter à confusion 😄 

Pour autant, ça reste lisible, et c'est ce qui m'importe ici.

Pour mieux comprendre ce que chaque status ou type veut dire, tu as ce fichier : `types/index.ts` qui aide bien.

```
export type LaneType =
| 'bidirectionnelle'
| 'bilaterale'
| 'voie-bus'
| 'voie-bus-elargie'
| 'velorue'
| 'voie-verte'
| 'bandes-cyclables'
| 'zone-de-rencontre'
| 'aucun'
| 'inconnu';

export type LaneStatus = 'done' | 'wip' | 'planned' | 'postponed' | 'unknown' | 'variante' | 'variante-postponed';
```

**Comment by XioNoX** [comment]
Ça roule, je m'y suis bien habitué depuis :)
