### ISSUE TITLE
Masquer `Fréquentation max 2030` si `trafic` n'est pas défini

### ISSUE THREAD

**Issue by XioNoX** [benoitdemaegdt/voieslyonnaises#415]
Il est pour l'instant obligé de définir la variable `trafic` dans ligne-X.md, sinon ça affiche:
` Fréquentation max 2030: ` sans valeur.

Serait-ce possible de masquer cette ligne si `trafic` n'est pas défini ?

Merci

**Comment by benoitdemaegdt** [comment]
Hello @XioNoX  👋 

Bonne remarque oui. Nous on a cette info à Lyon, mais j'imagine que c'est peu commun.

Je viens de passer le changement. ça donne donc ça si l'info n'est pas renseignée 👇 

<img width="844" alt="image" src="https://github.com/user-attachments/assets/f68bcade-5ba6-41b4-9165-ae78a0a09365">
