### ISSUE TITLE
[bouteille à la mer] Besoin d'aide sur un bug du fork  de Montpellier en l'absence de TFCx

### ISSUE THREAD

**Issue by DenisFeurer** [benoitdemaegdt/voieslyonnaises#438]
Hello !

Comme @TFCx l'a indiqué dans d'autres message, je contribue au Fork [TFCx/observatoire-velo-montpellier](https://github.com/TFCx/observatoire-velo-montpellier), mais avec beaucoup moins de compétence en développement :'-). Ces temps-ci @TFCx a peu de dispo et on prévoit une publication prochaine du site à l'occasion de la semaine de la mobilité et de notre grande manif actuelle, ce qui pourrait permettre de donner une résonance médiatique importante au site d'observatoire.

Le bug est lié à une fonctionnalité que nous avons ajouté à Montpellier => la visualisation par qualité d'aménagement (hyper importante pour notre plaidoyer local, et probablement intéressante pour d'autres villes).

Voici le bug que je souhaiterais pouvoir corriger, il concerne la page https://observatoire-velo-montpellier.netlify.app/evolution : 
- à l'arrivée sur la page le bouton radio "qualité du réseau" est coché ; les couleurs représentent les couleurs des Vélolignes
- si on clique sur le bouton radio "de la qualité des aménagements", ça marche => les couleurs représentent alors la qualité de la section
- si on clique en bas sur le bouton "<2021" => la visualisation sur la carte revient à la visualisation du réseau avec une couleur par ligne plutôt qu'une couleur en fonction des aménagements mais le bouton radio reste coché sur "de la qualité des aménagements" (et la légende reste celle de la qualité des lignes)

Savez-vous comment je pourrais me dépatouiller de ça ?

Merci d'avance et mes excuses si poster ici comme ça n'est pas ce qui est attendu de cet espace "issues".

**Comment by TFCx** [comment]
On a trouvé une solution (pas tout à fait parfaite) mais qui convient. On peut fermer normalement :)

**Comment by benoitdemaegdt** [comment]
Hello tous les deux 👋 

Tout d'abord mes félicitations pour le lancement de votre plateforme. C'est un très bel accomplissement et j'ai hâte de suivre les évolutions 🙌 

Concernant cette issue, je n'ai malheureusement pas eu le temps de regarder. Top que vous ayez trouvé une solution 🙌 

Je clôture donc :)
