### ISSUE TITLE
Le déploiement sur Netlify ne fonctionne plus

### ISSUE THREAD

**Issue by piersbarrios** [benoitdemaegdt/voieslyonnaises#478]
Bonjour, 

Le déploiement du projet sur Netlify fonctionnait bien jusqu'à récemment. 
Désormais, il y a une erreur 500. Quand je regarde du côté log, j'ai les messsages suivants:
```
Nov 16, 11:14:35 AM: e9aca6b6 ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module '@vue/devtools-api'
Require stack:
- /var/task/server.mjs
Nov 16, 11:14:35 AM: e9aca6b6 ERROR  [nuxt] [request error] [unhandled] [500] _createApp is not a function
```
Voici la capture d'écran:
![image](https://github.com/user-attachments/assets/9c1647ec-3052-4bb7-9d4b-ad32a35c76f0)

Je vais essayer de retrouver le commit qui a casé le déploiement mais je n'aurais pas les compétences pour dire ce qui a cassé dedans. :)

Merci, 
Piers 
(A Bicyclette Alençon, on est en train faire un fork)

**Comment by NoeABicyclette** [comment]
https://github.com/benoitdemaegdt/voieslyonnaises/commit/d24bf5c4a10e8b43a6e2ce7cf1c81676711096c4
Ce commit vient documenter le changement
